name: MacOS App CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test First Pipeline run
        run: echo "Hello World!"
